#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Titan — Post-Install Doctor
============================

Run after titan-configure.py (or any time) to check that a deployed Titan
harness is actually healthy: prerequisites present, MCP servers registered
with Claude Code, and every managed file titan-configure.py expects still
on disk. Also prints (and can write) a .mcp.json template appropriate for
the configured SCM provider.

Location note: lives alongside titan-configure.py in installer/ (not under
harness/scripts/) because, like titan-configure.py, it is meant to run
standalone at an arbitrary deployed workspace root — it is not part of the
managed harness content set that deploy-harness.sh copies into .claude/,
and it has the same "no pip dependency" constraint as the installer.

Usage:
    python titan-doctor.py [workspace]              # full check
    python titan-doctor.py --emit-mcp-json [workspace]
        Print the .mcp.json this workspace's platforms.scm.kind should use.
        Pass --write to also write it to <workspace>/.mcp.json (never
        overwrites an existing file — same never-clobber posture as
        deploy-harness.sh / titan-configure.py elsewhere in this toolkit).

Requires: Python 3.8+. Optionally node/git/claude on PATH for the checks
that need them (each check degrades to a warning, not a crash, if the
binary is missing — this is a diagnostic tool, it should never itself be
the reason a session can't start).
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

if sys.platform == "win32":
    import os
    os.system("")

G, C, Y, R, B, X = "\033[32m", "\033[36m", "\033[33m", "\033[31m", "\033[1m", "\033[0m"


def ok(m):   print(f"  {G}[OK]{X}  {m}")
def info(m): print(f"  {C}[..]{X}  {m}")
def warn(m): print(f"  {Y}[!!]{X}  {m}")
def err(m):  print(f"  {R}[XX]{X}  {m}")
def hdr(m):  print(f"\n  {B}{C}{m}{X}\n")
def rule():  print(f"  {'-' * 58}")


def run(cmd: str):
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except Exception as e:
        return 1, "", str(e)


# ── titan.config.json loader — duplicated minimal reader, same rationale as
# titan-configure.py: this is a standalone script with a zero-pip-dependency
# constraint, so importing harness/hooks/titan_config.py (a hooks/-scoped
# module not guaranteed to be on sys.path from an arbitrary workspace root)
# is skipped in favor of the same few lines of json.loads both scripts share. ──
def load_titan_config(workspace: Path) -> dict:
    for candidate in (
        workspace / ".claude" / "titan.config.json",
        workspace / "harness" / "titan.config.json",
    ):
        if candidate.is_file():
            try:
                return json.loads(candidate.read_text(encoding="utf-8"))
            except Exception:
                continue
    return {}


def person_name(config: dict, pid: str) -> str:
    p = config.get("contacts", {}).get("people", {}).get(pid)
    if isinstance(p, dict) and p.get("name"):
        return p["name"]
    return pid


# ── EXPECTED_FILES — same single source of truth as titan-configure.py
# Phase 8 (.claude/.deployed-manifest.json, generated by deploy-harness.sh).
# Duplicated rather than imported for the same standalone-script reason as
# the config loader above; keep this function's logic identical to
# titan-configure.py's if either ever changes. ──
_FALLBACK_EXPECTED_FILES = [
    "CLAUDE.md",
    ".mcp.json",
    ".claude/settings.json",
    ".claude/settings.local.json",
    ".claude/hooks/session-start.py",
    ".claude/hooks/protect-secrets.py",
    ".claude/hooks/answer-cache.py",
    ".claude/data/build-map.json",
    ".claude/data/reviewer-map.json",
    ".claude/commands/roles/dev-mode.md",
    ".claude/subagents/code-reviewer.md",
]


def expected_files(workspace: Path) -> list[str]:
    manifest_path = workspace / ".claude" / ".deployed-manifest.json"
    if manifest_path.is_file():
        try:
            files = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", [])
            if files:
                return files
        except Exception:
            pass
    return _FALLBACK_EXPECTED_FILES


# ── .mcp.json template ───────────────────────────────────────────────────
#
# SCHEMA WARNING — preserved VERBATIM from the reference harness this was extracted
# from (do not paraphrase; it documents a real, already-occurred incident):
# "ONLY real MCP servers of type stdio | http | sse may appear under
# mcpServers — Claude Code validates this whole file against its config
# schema, and an entry with any other type (e.g. a documentation stub with
# "type":"builtin") fails validation and causes the ENTIRE file to be
# silently discarded, so NO server loads (RCA 2026-07-06)."
_SCHEMA_WARNING_RCA = (
    'ONLY real MCP servers of type stdio | http | sse may appear under mcpServers — '
    'Claude Code validates this whole file against its config schema, and an entry '
    'with any other type (e.g. a documentation stub with "type":"builtin") fails '
    'validation and causes the ENTIRE file to be silently discarded, so NO server '
    'loads (RCA 2026-07-06).'
)

# Also preserved (near-verbatim, only the workspace noun genericized) — the
# separate, equally real RCA about ${VAR} expansion, since it is why the ADO
# entry below is launched via a wrapper script and not npx directly. Kept
# per the Titan extraction plan's C.6: "Keep — its RCA reason applies to any
# ADO adopter."
_AUTH_RCA = (
    "AUTH: azure-devops is launched via the mcp-ado-launch.cjs wrapper (NOT npx "
    "directly) because Claude Code expands ${VAR} in this file only from the OS "
    "launch environment, NOT from settings.local.json — so ${AZURE_DEVOPS_PAT} "
    "silently expanded to empty and the server authenticated as the null identity "
    "(TF400813). The wrapper reads the PAT straight from settings.local.json on "
    "every launch, so the connection is launch-context-independent and stays "
    "intact with no OS env var and no re-login. Needs Node >= 18 on PATH; this "
    "doctor verifies registration via `claude mcp list`."
)


def build_mcp_json(config: dict) -> dict:
    scm = config.get("platforms", {}).get("scm", {})
    kind = scm.get("kind", "azure-devops")

    ado_entry = {
        "azure-devops": {
            "type": "stdio",
            "command": "node",
            "args": [".claude/scripts/mcp-ado-launch.cjs"],
        }
    }
    # No GitHub launch wrapper ships with this toolkit yet (the ${VAR}-expansion
    # RCA above is ADO-specific to how mcp-ado-launch.cjs was built) — the
    # github entry below is a plain npx stdio launch using the standard GitHub
    # MCP server env-var contract. If the same silent-null-identity failure
    # mode is ever observed for GitHub, port a wrapper the same way.
    github_entry = {
        "github": {
            "type": "stdio",
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-github"],
            "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_PAT}"},
        }
    }

    if kind == "github":
        active, alt_label, alt_entry = github_entry, "azure-devops", ado_entry
    else:
        active, alt_label, alt_entry = ado_entry, "github", github_entry

    doc = {
        "_description": (
            f"Project-scoped MCP servers for this workspace. {_SCHEMA_WARNING_RCA} "
            "Built-in claude.ai connectors (e.g. Atlassian Rovo, Figma) are NOT "
            "configured here: they are enabled in claude.ai connector settings and "
            "authenticate via OAuth on first use. Do not add them to this file as "
            "pseudo-entries."
        ),
        "mcpServers": active,
        "_alternative_scm_kind_example": {
            "_note": (
                f"Inert reference JSON, NOT a live mcpServers entry (see the schema "
                f"warning above — this key is deliberately outside mcpServers so it "
                f"cannot trip that validation). Currently configured platforms.scm.kind "
                f"is {kind!r}; this shows what the {alt_label} entry looks like. To "
                f"switch, move this object's contents into mcpServers above, set "
                f"platforms.scm.kind to {alt_label!r} in titan.config.json, and re-run "
                f"titan-doctor.py --emit-mcp-json to regenerate cleanly instead of "
                f"hand-editing."
            ),
            alt_label: alt_entry[alt_label],
        },
    }
    if kind != "github":
        doc["_auth_note"] = _AUTH_RCA
    return doc


# ── checks ────────────────────────────────────────────────────────────────

def check_prerequisites() -> bool:
    hdr("Prerequisites")
    healthy = True

    py_ver = sys.version_info
    if py_ver >= (3, 8):
        ok(f"Python {py_ver.major}.{py_ver.minor}.{py_ver.micro}")
    else:
        err(f"Python 3.8+ required, found {py_ver.major}.{py_ver.minor}")
        healthy = False

    for label, cmd, min_note in (
        ("git", "git --version", None),
        ("node", "node --version", "v16+ recommended"),
        ("npm", "npm --version", None),
        ("claude", "claude --version", "Claude Code CLI"),
    ):
        rc, out, _ = run(cmd)
        if rc == 0:
            ok(f"{label}: {out}")
        else:
            warn(f"{label} not found on PATH" + (f" ({min_note})" if min_note else ""))
            if label in ("git", "claude"):
                healthy = False
    rule()
    return healthy


def check_mcp_registration(config: dict) -> bool:
    hdr("MCP Server Registration")
    scm_kind = config.get("platforms", {}).get("scm", {}).get("kind", "azure-devops")
    rc, out, err_msg = run("claude mcp list")
    if rc != 0:
        warn(f"`claude mcp list` failed ({err_msg or 'claude not on PATH'}) — cannot verify registration")
        rule()
        return False
    if scm_kind and scm_kind in out:
        ok(f"MCP server '{scm_kind}' registered (`claude mcp list`)")
        registered = True
    else:
        warn(f"MCP server '{scm_kind}' NOT found in `claude mcp list` output")
        info("Check .mcp.json at the workspace root and restart the session.")
        registered = False
    rule()
    return registered


def check_deployed_files(workspace: Path) -> bool:
    hdr("Deployed File Verification")
    files = expected_files(workspace)
    manifest_path = workspace / ".claude" / ".deployed-manifest.json"
    if manifest_path.is_file():
        info(f"Source: {manifest_path.relative_to(workspace)} ({len(files)} files)")
    else:
        warn(f"{manifest_path.name} not found — using the small fallback list instead of "
             "deploy-harness.sh's actual layout. Re-run deploy-harness.sh to get the full manifest.")
    missing = [f for f in files if not (workspace / f).is_file()]
    for f in files:
        if f not in missing:
            ok(f)
    for f in missing:
        warn(f"MISSING: {f}")
    rule()
    return not missing


def cmd_emit_mcp_json(config: dict, workspace: Path, write: bool) -> int:
    doc = build_mcp_json(config)
    text = json.dumps(doc, indent=2) + "\n"
    print(text)
    if write:
        dst = workspace / ".mcp.json"
        if dst.exists():
            warn(f"{dst} already exists — not overwritten. Diff manually or remove it first.")
            return 1
        dst.write_text(text, encoding="utf-8")
        ok(f"Wrote {dst}")
    return 0


def main(argv: list[str]) -> int:
    args = set(argv)
    positional = [a for a in argv if not a.startswith("-")]
    workspace = Path(positional[0] if positional else ".").resolve()

    if "--help" in args or "-h" in args:
        print(__doc__)
        return 0

    config = load_titan_config(workspace)
    org_brand = config.get("org", {}).get("harness_brand", "Titan")

    print(f"\n  {C}{'=' * 58}{X}")
    print(f"  {B}{C}  {org_brand} — Post-Install Doctor{X}")
    print(f"  {C}{'=' * 58}{X}")
    print(f"  {C}  Workspace: {workspace}{X}\n")

    if not config:
        warn("No .claude/titan.config.json found — checks below use generic fallbacks.")
    elif not config.get("configured", False):
        warn("titan.config.json has configured:false — this is still the shipped placeholder.")

    if "--emit-mcp-json" in args:
        return cmd_emit_mcp_json(config, workspace, write="--write" in args)

    healthy = True
    healthy &= check_prerequisites()
    healthy &= check_mcp_registration(config)
    healthy &= check_deployed_files(workspace)

    hdr("Summary")
    if healthy:
        ok("Doctor found no problems.")
    else:
        gov_owner = person_name(config, config.get("roles", {}).get("governance_owner", ""))
        warn("Doctor found problems — see warnings above.")
        info(f"If none of this makes sense, contact {gov_owner} (governance owner).")
    print(f"\n  {C}{'=' * 58}{X}\n")
    return 0 if healthy else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
